application:
  products:
    api-url: http://products.org
  feign:
    retry-interval: 1000
    retry-max-attempts: 3
feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
        error-decoder: com.mariusz.orlowicz.utils.CustomFeignErrorDecoder
        retryer: com.mariusz.orlowicz.utils.CustomFeignRetry
        loggerLevel: basic
logging:
  level:
    com.mariusz.orlowicz.model.infrastructure: DEBUG
